.TH AT89PROG 1 "24 February 2004"
.SH NAME
at89prog \- command-line utility for programming the AT89S8252 processor 
over the serial port
.SH SYNOPSIS
\fBat89prog\fP [\fIflags\fP] command [arguments]

.SH DESCRIPTION
\fBat89prog\fP is a command-line utility that can be used to manipulate 
the code and data memory on a AT89S8252 processor (and similar).
The programmer currently only works with programmers working over 
the serial port, though support for parallel ports may be added in the future.

\fBat89prog\fP can write, read, erase and lock the code and data memory of the 
microcontroller.

.SH COMMANDS

.TP
\fIerase\fP
Erases both the code and the data memory of the controller. All bytes will
be filled with 0xFF (255).

.TP
\fIreset\fP
Only reset the device. Restarts currently running program.

.TP
\fIlock <level>\fP
Sets lock on the code and data memory. Available levels are:
.PP
2 - External movc access to internal code bytes is not possible. The 
device is write-protected.
.PP
3 - Same as 2, but the device is now read-protected as well.
.PP
4 - Same as 3, but external execution is no longer possible either.
.IP

.TP
\fIwritefile [file] ...\fP
Write the specified file(s) to the device. The file should be in the format 
specified by \fB--format\fP. If a file specified is '-', data will be read 
from standard in(stdin).

.TP
\fIreadfile <len> [file]\fP
Read \fB<len>\fP number of bytes and store them in the specified file. If
no file was specified, the bytes will be written to stdout.

.TP
\fIwritebyte <address> <byte>\fP
Write the specified \fB<byte>\fP at the specified memory \fB<address>\fP.

.TP
\fIreadbyte <address>\fP
Read the byte at the specified address and output it.

.TP
\fIversion\fP
Print version information.

.SS OPTIONS
.TP
\fI--help\fP
Help: show syntax.
.TP
\fI-d, --data-memory\fP
Execute the specified command on the data memory instead of on the code 
memory.
.TP
\fI-c, --code-memory\fP
Execute the specified command on the colde memory. This is the default.
.TP
\fI-f, --format=hex,bin,auto\fP
Specify the format the input files are in. Auto tries to figure out the type 
of the file based on the first character (a colon indicates Intel hex). The 
default is auto.
.TP
\fI-i, --ignore-chk\fP
Do not wait for the CHK line to follow the RST (reset) line. On some boards 
CHK always follows the state of RST and this can be used as a way of verifying 
that the device is connected properly.
.TP
\fI-p, --port=LOCATION\fP
Use the serial device at the specified location. Should be a hexadecimal address for serial-raw and parallel and a device name (such as /dev/ttyS0 or /dev/ttyUSB0) for 
serial.
.TP
\fI-r, --rcfile=FILE\fP
Read from the specified rcfile instead of from the \fB.at89progrc\fP file 
in the users' home directory.
.TP
\fI-t, --type=serial|serial-raw|parallel\fP
Driver to use. \fBserial\fP uses the standard serial port functionality. 
\fBserial-raw\fP and \fBparallel\fP talk directly to the hardware and therefor requires root privileges. 
Only use serial-raw if you have a buggy serial port driver.
.TP
\fI-v,--verbose\fP
Be verbose.
.TP
\fI--verify\fP
When writing a byte to the memory, read the byte back to check whether 
the write was successful.

.SH SEE ALSO
\fBat89progrc(5), ponyprog(1)\fP

.SH AUTHOR
\fBat89prog\fP and this man page were written by Jelmer Vernooij. 

.SH THANKS
Thanks to Hans Tjeerdsma for his help with debugging the output functions and 
and for his help with the research.
