.TH AT89PROGRC 1 "1 February 2004"
.SH NAME
at89progrc \- configuration file for the at89prog programmer
.SH SYNTAX
All lines consistent of a key and value pair. Comments and empty lines are 
not allowed.

.SH KEYS
The following keys are available:

.TP
\fItype\fP
Type of port. Available values: serial, serial-raw, parallel

.TP
\fIport\fP
Base address of port in case of serial-raw and parallel (such as 2f8, 378, etc). Path for serial (/dev/ttyS0, /dev/ttyUSB0).

.TP
\fIMOSI\fP
Specify on what pin the Master Out, Slave In line is connected. See \fBPINS\fP below for possible values.

.TP
\fIMISO\fP
Specify on what pin the Master In, Slave Out line is connected. See \fBPINS\fP below for possible values.

.TP
\fIRST\fP
Specify on what pin the Reset line is connected. See \fBPINS\fP below for possible values.

.TP
\fICHK\fP
Specify on what pin the Check line is connected. See \fBPINS\fP below for possible values.

.TP
\fISCK\fP
Specify on what pin the Clock line is connected. See \fBPINS\fP below for possible values.


.SS PINS

.TP
All currently available pins for serial and serial-raw are listed below. To reverse a pin, put a ! (exclamation mark) before it's name.

.TP
.BR
RTS
.BR
TXD
.BR
CTS
.BR
DSR
.BR
DTR

.SH SEE ALSO
\fB
at89prog(1)
\fP

.SH AUTHOR
\fBat89prog\fP and this man page were written by Jelmer Vernooij. 
